defmodule Openmft.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:companies) do
      add :email, :text
      add :phone_number, :text
      add :billing_id, :text
      add :modified_by, :text
    end
  end

  def down do
    alter table(:companies) do
      remove :modified_by
      remove :billing_id
      remove :phone_number
      remove :email
    end
  end
end
